version: '3'
services:
  server:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      args:
        - PROJECT_OWNER=${PROJECT_OWNER}
        - PROJECT_NAME=${PROJECT_NAME}
        - SERVER_PORT=${SERVER_PORT}
    container_name: ${PROJECT_NAME}_server
    tty: true
    depends_on:
      - postgres
    env_file:
      - ${ENV_FILE}
    volumes:
      - .:/go/src/github.com/${PROJECT_OWNER}/${PROJECT_NAME}

  postgres:
    container_name: ${PROJECT_NAME}_db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    restart: always
